### ISSUE TITLE
[Para melhorar] Barra Menu Bloqueada

### ISSUE THREAD

**Issue by J999Ventura** [enear/extreme-program#15]
Quando carrego na barra de menu ela fica bloqueada mesmo depois de eu escolher uma opção, a não ser que volte a carregar na mesma
No telefone, este fenómeno atrapalha o utilizador. 
Quando escolho uma opção, a barra não sai automaticamente, se eu fizer scroll down ela atrabalha a minha navegação.
Era interessante, quando selecionada uma opção a barra sair automaticamente.

**Comment by snot-dev** [comment]
Olá João.

Penso ter corrigido este issue.

Obrigado
