### ISSUE TITLE
Update Goal description [big new feature]

### ISSUE THREAD

**Issue by eXecutable** [enear/extreme-program#3]
A goal in a period is only awarded once. But we need a way for people to keep submitting things they did in that period without extra awarded points...

**Comment by snot-dev** [comment]
Hi Jorge. I think I'll need a day or two to do this. Not only I need to  develop the logic for this, but also need to make several UI changes and warnings regarding this.

**Comment by snot-dev** [comment]
Hi Jorge,

This is done now. If the checkbox 'Award points only once" for a goal, in the backoffice is checked, and a user submits a request more than once for that goal, an alert will appear, warning the user that he can only earn points once for that goal, and a request is sent with 0 points.

Thank you
